Add native global menu support (macOS)
MewPurPur/GodSVG pull request #644
Opened 2024-04-09 20:20 UTC by aaronfranke

Draft because I used the new Godot 4.3+ API so this will only work with Godot 4.3+. Follow-up to #643.

<img width="800" alt="Screenshot 2024-04-09 at 4 33 47 AM" src="https://github.com/MewPurPur/GodSVG/assets/1646875/80b939c1-f610-4984-9274-797f9e67db86">
<img width="800" alt="Screenshot 2024-04-09 at 4 34 07 AM" src="https://github.com/MewPurPur/GodSVG/assets/1646875/257e169b-2364-4713-ac15-3bba04c16183">
<img width="800" alt="Screenshot 2024-04-09 at 4 34 17 AM" src="https://github.com/MewPurPur/GodSVG/assets/1646875/36fb9103-0303-41d4-b848-32f22ce1a285">
<img width="800" alt="Screenshot 2024-04-09 at 4 34 29 AM" src="https://github.com/MewPurPur/GodSVG/assets/1646875/0ea7c3c0-1604-4ecd-8410-c3e058fd6f79">
<img width="800" alt="Screenshot 2024-04-09 at 4 33 14 AM" src="https://github.com/MewPurPur/GodSVG/assets/1646875/36b8e111-2e9b-47b8-bb96-41fd4f9dd9f9">

2024-04-13 13:15 UTC, MewPurPur commented
Took a peek today, this seems too hard-coded. The shortcuts are only assigned on tree enter, and they don't seem to account for the user has changing the shortcuts. If necessary, you can add a custom notification for changed shortcuts in Utils.gd and listen to it here, fetching the first shortcut from each action instead.

I don't know the new 4.3 functionality though, maybe that's not possible.

2024-05-05 18:39 UTC, MewPurPur commented
Needs to be updated after #711.

Please check out the TranslationUtils class!

2024-06-06 22:40 UTC, MewPurPur commented
We're on a 4.3 beta now, this can be considered

2024-06-07 06:04 UTC, aaronfranke commented
> (wait, what happened to this PR?)

It looks like you somehow managed to edit a commit from way back in the history, and force-push, which modified all commits beyond that point too. Don't worry, I can fix it easily, that is, whenever I get around to working on this.

2024-06-07 06:43 UTC, MewPurPur commented
Okay, thanks! Yeah, I was doing some weird things to delete a file from the git history (a file which is no longer in the repo or even relevant, but made 80% of its size).

2024-07-22 19:23 UTC, MewPurPur requested changes
TranslationUtils.get_shortcut_description() should be used where possible. Also, there's a SHORTCUTS_CHANGED custom notification now - the signal isn't needed. _action_call(action) could also be replaced with ShortcutUtils.fn(action).call().

Could you also replace the remaining tr() calls with TranslationServer.translate()? We decided recently to always use this version because it can be used in static functions.

Also open the "update_translations.gd" script to update translations automatically after you're done.

btw we're already on the 4.3 betas, so this will work.

2024-07-23 01:39 UTC, aaronfranke commented
> TranslationUtils.get_shortcut_description() should be used when it can.

Done.

> Also, there's a SHORTCUTS_CHANGED custom notification now - the signal isn't needed.

I'm not sure, it doesn't seem the same. Also, isn't a notification worse than a signal? A notification is propagated to everything, while a signal is only propagated to what connects to it.

> _action_call(action) could also be replaced with ShortcutUtils.fn_call(action).

I don't think so? `ShortcutUtils.fn_call` doesn't handle everything.

> Could you also replace the remaining tr() calls with TranslationServer.translate() instead?

Done.

> Also open the "update_translations.gd" script to update translations automatically after you're done.

Done (and I discarded changes to the po/pot files made before running this script, so the changes to the po/pot files in this PR are purely from the script).

2024-07-23 06:27 UTC, MewPurPur commented on src/ui_parts/global_menu.gd
> +	# Included App and Help menus.
TranslationUtils should be used here to get the translated string of "open_settings". Same for the lines of code below. That way it's ensured that they are the same everywhere.

2024-07-23 08:04 UTC, MewPurPur commented
Thanks!

2024-07-23 08:04 UTC, merged